# Generated by Django 6.0.6 on 2026-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
