# Generated by Django 6.0.6 on 2026-06-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='profile',
        ),
    ]
