# Generated by Django 6.0.6 on 2026-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('Email', models.EmailField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('Phone', models.PositiveIntegerField(max_length=12)),
            ],
        ),
    ]
